"""empty message

Revision ID: 5c12f3ec5a1d
Revises: 36fbd53a38c8
Create Date: 2024-09-22 10:45:15.127218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c12f3ec5a1d'
down_revision = '36fbd53a38c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_planets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_lifestatus_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_population_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planets_population_key', ['population'])

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('characters_lifestatus_key', ['lifestatus'])

    op.drop_table('favorites_planets')
    # ### end Alembic commands ###
